media:
  input: assets/images/blog
  output: /assets/images/blog

content:
  - name: posts
    label: Blog posts
    type: collection
    path: blog
    filename: "{primary}.md"
    view:
      fields: [title, date, category]
      primary: title
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: intro
        label: Short intro (shown under the title and on the blog list)
        type: string
      - name: date
        label: Date
        type: date
        required: true
      - name: category
        label: Category
        type: select
        options:
          values: [Projekty, Ogłoszenia, Scenariusze, Pomysły]
      - name: featuredImage
        label: Featured image
        type: image
        required: true
      - name: body
        label: Content
        type: rich-text
